# Generated by Django 5.2.3 on 2025-08-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_app_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
