# Generated by Django 5.2.3 on 2025-08-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_submission_approved"),
    ]

    operations = [
        migrations.RemoveField(model_name="app", name="play_store_link",),
        migrations.AddField(
            model_name="app",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="apps"),
        ),
    ]
