# Generated by Django 5.2.3 on 2025-09-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userpoints", name="app",),
        migrations.RemoveField(model_name="userpoints", name="user",),
        migrations.DeleteModel(name="App",),
        migrations.DeleteModel(name="UserPoints",),
    ]
